name: adquisicion_de_datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:

      - name: Checkout del repositorio
        uses: actions/checkout@v4


      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

 
      - name: paso 1 - Crear y activar entorno virtual
        run:  python -m venv venv

      - name: activar entorno virtual  
        run:  venv/Scripts/activate

      - name: paso 2 - actualizar pip
        run:  python -m pip install --upgrade pip

      - name: paso 3 - Instalar dependencias
        run:  pip install -e .

      - name: paso 4 -  Ejecutar script principal (collector.py)
        run:  python src/SSE_Composite/collector.py  

      - name: paso 5 -  Ejecutar enriquecimiento de datos (enricher.py)
        run:  python src/SSE_Composite/enricher.py

      - name: paso 6 -  Ejecutar el modelo de predicción (Modeller.py)
        run: |
          python src/SSE_Composite/modeller.py --train
          python src/SSE_Composite/modeller.py --predict

      - name: paso 7 -  Exportar dashboard (dashboard.py)
        run:  python src/SSE_Composite/dashboard.py --export

      - name: Sincronizar main antes de commitear
        run: |
          cd src/SSE_Composite
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main  

      - name: Commit artefactos al repo
        run: |
          cd src/SSE_Composite
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add artifacts/
          git commit -m "chore: agregar reportes estáticos de KPI"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit y Push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: adquisicion de datos
          commit_user_name: estcardenasveloth [GitHub Actions]
          commit_user_email: julio.cardenas@est.iudigital.edu.co
          commit_author: Julio Cardenas <julio.cardenas@est.iudigital.edu.co>
